In [71]:
import torch

In [72]:
x=torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [73]:
x.shape

torch.Size([12])

In [74]:
x.numel()

12

In [75]:
# 为什么「行」在前？
# Python 和 NumPy 遵循的约定是：数组的形状（shape）是 (行数, 列数)。
#
# 也就是 (高度，高度方向的元素数量, 宽度方向的元素数量)。
#
# 这和数学中的矩阵一致 —— 一个 𝑚×𝑛 的矩阵有 m 行、n 列。   高维<-----低维
y=x.reshape(3,4)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [76]:
y[:]=1
y

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [77]:
x

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [78]:
x.reshape(2,2,3)

tensor([[[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]]])

In [79]:
torch.ones((2,2,3),dtype=torch.int)

tensor([[[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]]], dtype=torch.int32)

In [80]:
torch.zeros((1,2))

tensor([[0., 0.]])

In [81]:
torch.tensor([[1,2,3],[1,3,3]])

tensor([[1, 2, 3],
        [1, 3, 3]])

In [82]:
torch.randn((2,3))

tensor([[-0.4820,  1.7451,  0.3943],
        [ 0.4023,  0.8529,  1.0891]])

In [83]:
torch.randn(2,3)

tensor([[-1.4056, -0.8135,  0.4870],
        [ 0.5893, -0.2498,  0.7884]])

In [84]:
x=torch.tensor([1,2,3])
y=torch.tensor([4,5,6])
x-y,x+y,x*y,x/y,x**y

(tensor([-3, -3, -3]),
 tensor([5, 7, 9]),
 tensor([ 4, 10, 18]),
 tensor([0.2500, 0.4000, 0.5000]),
 tensor([  1,  32, 729]))

In [85]:
x=torch.arange(12).reshape(2,6)
torch.exp(x)

tensor([[1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02],
        [4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04]])

In [86]:
y=torch.arange(12,24).reshape((2,6))
torch.cat((x,y),dim=0),torch.cat((x,y),dim=1)

(tensor([[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11],
         [12, 13, 14, 15, 16, 17],
         [18, 19, 20, 21, 22, 23]]),
 tensor([[ 0,  1,  2,  3,  4,  5, 12, 13, 14, 15, 16, 17],
         [ 6,  7,  8,  9, 10, 11, 18, 19, 20, 21, 22, 23]]))

In [87]:
x==y

tensor([[False, False, False, False, False, False],
        [False, False, False, False, False, False]])

In [88]:
x.sum(),y.sum()

(tensor(66), tensor(210))

In [89]:
torch.cat((x,y),dim=0).numel()

24

In [90]:
x=torch.arange(12).reshape(2,6)
y=torch.randn(2,6)
x,y,x>y

(tensor([[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11]]),
 tensor([[ 1.1217,  1.0190,  0.6886, -0.2186,  1.4548,  0.2306],
         [-0.2670, -1.5979,  1.2440,  1.1305,  0.4285, -0.3943]]),
 tensor([[False, False,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True]]))

In [91]:
x>y

tensor([[False, False,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True]])

In [92]:
x=torch.arange(12)
y=torch.arange(12).reshape(12,1)
x+y

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
        [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
        [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
        [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
        [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
        [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
        [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]])

In [93]:
z = x + y
type(z)
z[0::2]

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
        [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
        [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
        [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]])

In [94]:
print(id(z))
z[:]=torch.arange(12*12).reshape(12,12)
print(id(z))

4638579904
4638579904


In [95]:
type([1,2])

list

In [103]:
x=torch.arange(12).reshape(1,12,1)
y=torch.ones(4).reshape(2,1,2)
x,y,x+y

(tensor([[[ 0],
          [ 1],
          [ 2],
          [ 3],
          [ 4],
          [ 5],
          [ 6],
          [ 7],
          [ 8],
          [ 9],
          [10],
          [11]]]),
 tensor([[[1., 1.]],
 
         [[1., 1.]]]),
 tensor([[[ 1.,  1.],
          [ 2.,  2.],
          [ 3.,  3.],
          [ 4.,  4.],
          [ 5.,  5.],
          [ 6.,  6.],
          [ 7.,  7.],
          [ 8.,  8.],
          [ 9.,  9.],
          [10., 10.],
          [11., 11.],
          [12., 12.]],
 
         [[ 1.,  1.],
          [ 2.,  2.],
          [ 3.,  3.],
          [ 4.,  4.],
          [ 5.,  5.],
          [ 6.,  6.],
          [ 7.,  7.],
          [ 8.,  8.],
          [ 9.,  9.],
          [10., 10.],
          [11., 11.],
          [12., 12.]]]))