In [14]:
import torch
x = torch.tensor(3)
y = torch.tensor(4)
x,y,x+y

(tensor(3), tensor(4), tensor(7))

In [15]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
len(x)

10

In [17]:
x.shape

torch.Size([10])

In [18]:
x=torch.arange(20).reshape(2,10)
x

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [19]:
x.T

tensor([[ 0, 10],
        [ 1, 11],
        [ 2, 12],
        [ 3, 13],
        [ 4, 14],
        [ 5, 15],
        [ 6, 16],
        [ 7, 17],
        [ 8, 18],
        [ 9, 19]])

In [20]:
torch.zeros(2,10)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [33]:
z=torch.arange(12).reshape(2,2,3)
z,z.sum(2)

(tensor([[[ 0,  1,  2],
          [ 3,  4,  5]],
 
         [[ 6,  7,  8],
          [ 9, 10, 11]]]),
 tensor([[ 3, 12],
         [21, 30]]))

In [35]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [36]:
B=A.sum(0,keepdim=True)
B

tensor([[40., 45., 50., 55.]])

In [37]:
A/B

tensor([[0.0000, 0.0222, 0.0400, 0.0545],
        [0.1000, 0.1111, 0.1200, 0.1273],
        [0.2000, 0.2000, 0.2000, 0.2000],
        [0.3000, 0.2889, 0.2800, 0.2727],
        [0.4000, 0.3778, 0.3600, 0.3455]])

In [39]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [38]:
A.cumsum(0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [42]:
A=torch.arange(10)
B=A+1
A,B

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [43]:
torch.dot(A,B)

tensor(330)

In [45]:
A=torch.arange(10).reshape(5,2)
B=torch.arange(2)
A,B,torch.mv(A,B)

(tensor([[0, 1],
         [2, 3],
         [4, 5],
         [6, 7],
         [8, 9]]),
 tensor([0, 1]),
 tensor([1, 3, 5, 7, 9]))

In [47]:
A=torch.arange(10).reshape(5,2)
B=torch.arange(12).reshape(2,6)
A,B,torch.mm(A,B)

(tensor([[0, 1],
         [2, 3],
         [4, 5],
         [6, 7],
         [8, 9]]),
 tensor([[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11]]),
 tensor([[  6,   7,   8,   9,  10,  11],
         [ 18,  23,  28,  33,  38,  43],
         [ 30,  39,  48,  57,  66,  75],
         [ 42,  55,  68,  81,  94, 107],
         [ 54,  71,  88, 105, 122, 139]]))

In [48]:
A=torch.arange(10).reshape(5,2)
B=A.T.T
torch.equal(A,B)

True

In [49]:
A=torch.arange(10).reshape(5,2)
B=torch.arange(10,20).reshape(5,2)

torch.equal(A.T+B.T,(A+B).T)

True

In [51]:
A=torch.arange(36).reshape(6,6)
A.T+A

tensor([[ 0,  7, 14, 21, 28, 35],
        [ 7, 14, 21, 28, 35, 42],
        [14, 21, 28, 35, 42, 49],
        [21, 28, 35, 42, 49, 56],
        [28, 35, 42, 49, 56, 63],
        [35, 42, 49, 56, 63, 70]])

In [52]:
len(torch.arange(2*3*4).reshape(2,3,4))

2

In [56]:
A=torch.arange(20).reshape(1,20)
A,A.sum(1),A/A.sum(1)

(tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
          18, 19]]),
 tensor([190]),
 tensor([[0.0000, 0.0053, 0.0105, 0.0158, 0.0211, 0.0263, 0.0316, 0.0368, 0.0421,
          0.0474, 0.0526, 0.0579, 0.0632, 0.0684, 0.0737, 0.0789, 0.0842, 0.0895,
          0.0947, 0.1000]]))