In [6]:
import torch
x=torch.arange(0,10,dtype=torch.float)
x.requires_grad_(True)
y=2*torch.dot(x,x)
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12., 16., 20., 24., 28., 32., 36.])

In [14]:
import torch
x=torch.arange(10)
y= len(x)
x,y,torch.dot(x,x)

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 10, tensor(285))

In [45]:
import torch
x=torch.arange(10.0)
x.requires_grad_(True)
y=torch.dot(x,x*x)
y.backward()
x.grad

tensor([  0.,   3.,  12.,  27.,  48.,  75., 108., 147., 192., 243.])

In [47]:
dir(torch.Use)

['__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'isAfter',
 'offset',
 'user']