以下是**仅包含 PyTorch** 的张量基础与操作知识点整理，去除了其他框架内容，方便专注使用 PyTorch 学习张量相关内容。

---

# 张量基础与操作（PyTorch版）

## 1. 张量介绍

* **张量（Tensor）**：多维数组，是深度学习中存储和操作数据的主要工具。
* PyTorch 中的张量类是 `torch.Tensor`，其 API 与 NumPy 类似。
* 相较 NumPy，PyTorch 的张量：

  * 支持 GPU 加速；
  * 支持自动微分；
  * 更适合深度学习任务。

## 2. 创建张量

In [3]:
import torch

* **一维张量**（向量）：

In [7]:
  x = torch.arange(12)
  x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

* **查看形状和元素总数**：

In [8]:
  x.shape        # torch.Size([12])
    # 12

torch.Size([12])

In [9]:
  x.numel()

12

* **改变形状（reshape）**：

In [11]:
x.reshape(3, 4)  # 变为 3 行 4 列


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [12]:
x.reshape(-1, 4)  # 自动计算行数

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [13]:
x.numel()

12

* **特殊张量初始化**：

In [ ]:
  torch.zeros((2, 3, 4))
  torch.ones((2, 3, 4))
  torch.randn(3, 4)  # 从标准正态分布采样
  torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4]])  # 通过列表定义

## 3. 基本运算

* **按元素运算**（elementwise）：

In [14]:
  x = torch.tensor([1.0, 2, 4, 8])
  y = torch.tensor([2.0, 2, 2, 2])
  x + y, x - y, x * y, x / y, x ** y
  torch.exp(x)  # e^x

tensor([ 2.,  4.,  8., 16.])

* **矩阵操作**（点积、矩阵乘法）详见后续线性代数章节。

## 4. 张量连接（拼接）

In [16]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0)  # 沿行连接
torch.cat((X, Y), dim=1)  # 沿列连接

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

## 5. 逻辑运算

In [17]:
X == Y      # 相等判断，返回布尔张量
X < Y       # 小于判断
X > Y       # 大于判断

tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

## 6. 汇总操作

In [18]:
X.sum()     # 所有元素求和

tensor(66.)

## 7. 广播机制（Broadcasting）

In [ ]:
a = torch.arange(3).reshape((3, 1))  # 3x1
b = torch.arange(2).reshape((1, 2))  # 1x2
a + b  # 通过广播得到 3x2

## 8. 索引与切片

* **读取元素**：

In [ ]:
  X[-1]       # 最后一行
  X[1:3]      # 第2~3行

* **写入元素**：

In [ ]:
  X[1, 2] = 9
  X[0:2, :] = 12

## 9. 内存优化（原地操作）

* **一般操作会开辟新内存**：

In [ ]:
  before = id(Y)
  Y = Y + X
  id(Y) == before  # False

* **使用切片原地更新**：

In [ ]:
  Z = torch.zeros_like(Y)
  Z[:] = X + Y  # 原地修改 Z

* **用 += 实现原地更新**：

In [ ]:
  before = id(X)
  X += Y
  id(X) == before  # True

## 10. 转换为 Python 对象

* **Tensor <=> NumPy**（共享内存）：

In [20]:
  A = X.numpy()
  B = torch.tensor(A)
  type(A), type(B)

(numpy.ndarray, torch.Tensor)

* **Tensor => Python 标量**：

In [19]:
  a = torch.tensor([3.5])
  a.item(), float(a), int(a)

(3.5, 3.5, 3)

---

## 小结

* 张量是深度学习中最基础的数据结构。
* PyTorch 提供了高效的张量创建、索引、广播、数学操作等功能。
* 熟练掌握张量操作是学习深度学习的基础。

---

如果你还想继续整理“线性代数”、“自动微分”等 PyTorch 相关基础内容，也可以告诉我。