In [44]:
import torch

In [45]:
x=torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [46]:
x.shape

torch.Size([12])

In [47]:
x.numel()

12

In [48]:
# 为什么「行」在前？
# Python 和 NumPy 遵循的约定是：数组的形状（shape）是 (行数, 列数)。
#
# 也就是 (高度，高度方向的元素数量, 宽度方向的元素数量)。
#
# 这和数学中的矩阵一致 —— 一个 𝑚×𝑛 的矩阵有 m 行、n 列。   高维<-----低维
x.reshape(3,4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [49]:
x.reshape(2,2,3)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])

In [50]:
torch.ones((2,2,3),dtype=torch.int)

tensor([[[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]]], dtype=torch.int32)

In [51]:
torch.zeros((1,2))

tensor([[0., 0.]])

In [52]:
torch.tensor([[1,2,3],[1,3,3]])

tensor([[1, 2, 3],
        [1, 3, 3]])

In [53]:
torch.randn((2,3))

tensor([[-0.2022, -1.1585,  1.5754],
        [-0.5123, -1.0920,  0.8043]])

In [54]:
torch.randn(2,3)

tensor([[ 1.0029, -1.3379, -0.6250],
        [ 0.6278, -0.5793, -0.8176]])

In [55]:
x=torch.tensor([1,2,3])
y=torch.tensor([4,5,6])
x-y,x+y,x*y,x/y,x**y

(tensor([-3, -3, -3]),
 tensor([5, 7, 9]),
 tensor([ 4, 10, 18]),
 tensor([0.2500, 0.4000, 0.5000]),
 tensor([  1,  32, 729]))

In [56]:
x=torch.arange(12).reshape(2,6)
torch.exp(x)

tensor([[1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02],
        [4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04]])

In [57]:
y=torch.arange(12,24).reshape((2,6))
torch.cat((x,y),dim=0),torch.cat((x,y),dim=1)

(tensor([[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11],
         [12, 13, 14, 15, 16, 17],
         [18, 19, 20, 21, 22, 23]]),
 tensor([[ 0,  1,  2,  3,  4,  5, 12, 13, 14, 15, 16, 17],
         [ 6,  7,  8,  9, 10, 11, 18, 19, 20, 21, 22, 23]]))

In [58]:
x==y

tensor([[False, False, False, False, False, False],
        [False, False, False, False, False, False]])

In [60]:
x.sum(),y.sum()

(tensor(66), tensor(210))

In [61]:
torch.cat((x,y),dim=0).numel()

24